# Generated by Django 5.2.4 on 2025-08-31 12:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_task', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Writings',
                'verbose_name_plural': 'Writings',
            },
        ),
        migrations.CreateModel(
            name='WritingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveBigIntegerField(default=1)),
                ('question', ckeditor.fields.RichTextField()),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_answers', to='writing.writing')),
            ],
            options={
                'verbose_name': 'Writing Question',
                'verbose_name_plural': 'Writing Questions',
            },
        ),
        migrations.CreateModel(
            name='WritingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_time', models.PositiveIntegerField(default=3600, verbose_name='Answer Time (seconds)')),
                ('test_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='writing',
            name='writing_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_materials', to='writing.writingmaterial'),
        ),
        migrations.CreateModel(
            name='WritingUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveBigIntegerField(default=1)),
                ('answer', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_user_answers', to=settings.AUTH_USER_MODEL)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='writing.writing')),
            ],
            options={
                'verbose_name': 'Writing Answer',
                'verbose_name_plural': 'Writing Answers',
                'unique_together': {('user', 'writing')},
            },
        ),
    ]
