# Generated by Django 5.2.4 on 2025-09-27 18:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_alter_writingmaterial_test_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writinguseranswer',
            name='feedback',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
