# Generated by Django 5.2.4 on 2025-10-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_alter_writinguseranswer_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingmaterial',
            name='answer_time',
            field=models.PositiveIntegerField(default=3600, help_text='Answer time (seconds)', verbose_name='Answer Time (seconds)'),
        ),
    ]
