# Generated by Django 5.2.4 on 2025-10-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_alter_writingmaterial_answer_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writinguseranswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Writing Answer', 'verbose_name_plural': 'Writing Answers'},
        ),
    ]
