# Generated by Django 5.2.4 on 2025-08-31 12:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_time', models.PositiveIntegerField(default=3600, verbose_name='Answer Time (seconds)')),
                ('test_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Reading Content')),
                ('questions', ckeditor.fields.RichTextField(verbose_name='Questions')),
                ('passage_number', models.PositiveIntegerField(choices=[(1, 'Passage 1'), (2, 'Passage 2'), (3, 'Passage 3')], verbose_name='Passage Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('reading_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_materials', to='reading.readingmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='User Answer')),
                ('is_true', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='reading.reading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_user_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Answer',
                'verbose_name_plural': 'Reading Answers',
            },
        ),
        migrations.CreateModel(
            name='ReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(default=1, verbose_name='Question Number')),
                ('true_answer', models.CharField(blank=True, max_length=500, null=True, verbose_name="Correct Answer's with (;)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='reading.reading')),
            ],
            options={
                'verbose_name': 'Reading Question',
                'verbose_name_plural': 'Reading Questions',
                'ordering': ['reading', 'question_number'],
                'unique_together': {('reading', 'question_number')},
            },
        ),
    ]
