# Generated by Django 5.2.4 on 2025-10-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_alter_readingmaterial_test_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='answer_time',
            field=models.PositiveIntegerField(default=3600, help_text='Answer time (seconds)', verbose_name='Answer Time (seconds)'),
        ),
    ]
