# Generated by Django 5.2.4 on 2025-10-31 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_readingmaterial_answer_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinguseranswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reading Answer', 'verbose_name_plural': 'Reading Answers'},
        ),
        migrations.AlterUniqueTogether(
            name='readinguseranswer',
            unique_together={('user', 'reading', 'question_number')},
        ),
    ]
