# Generated by Django 5.2.4 on 2025-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_readinguseranswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='questions',
            field=models.TextField(help_text='HTML content with custom question tags', verbose_name='Questions'),
        ),
    ]
