# Generated by Django 5.2.4 on 2025-12-06 21:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_alter_reading_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='questions_raw',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Stores original questions before parsing', null=True, verbose_name='Original Questions (Unparsed)'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='questions',
            field=ckeditor.fields.RichTextField(verbose_name='Questions'),
        ),
    ]
