# Generated by Django 5.2.4 on 2026-09-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_reading_questions_raw_alter_reading_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinganswer',
            name='true_answer',
            field=models.CharField(blank=True, help_text='MCQ: A. Open-ended: key phrases separated by ; . Personal/opinion: leave empty or write OPINION.', max_length=500, null=True, verbose_name="Correct Answer's with (;)"),
        ),
    ]
