# Generated by Django 5.2.4 on 2026-09-21 17:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0008_readinganswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='questions',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Questions'),
        ),
    ]
