# Generated by Django 5.2.4 on 2025-08-31 12:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time', models.PositiveIntegerField(default=5, verbose_name='Prep Time (seconds)')),
                ('answer_time', models.PositiveIntegerField(default=20, verbose_name='Answer Time (seconds)')),
                ('speaking_part', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Speakings',
                'verbose_name_plural': 'Speakings',
            },
        ),
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question', ckeditor.fields.RichTextField(verbose_name='Question')),
                ('speaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answer', to='speaking.speaking')),
            ],
            options={
                'verbose_name': 'Speaking Question',
                'verbose_name_plural': 'Speaking Questions',
            },
        ),
        migrations.CreateModel(
            name='SpeakingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('test_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='speaking',
            name='speaking_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sections', to='speaking.speakingmaterial'),
        ),
        migrations.AlterUniqueTogether(
            name='speaking',
            unique_together={('speaking_material', 'speaking_part')},
        ),
        migrations.CreateModel(
            name='SpeakingUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to='speaking_records/')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speaking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='speaking.speaking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_user_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speaking Answer',
                'verbose_name_plural': 'Speaking Answers',
                'unique_together': {('user', 'speaking')},
            },
        ),
    ]
