# Generated by Django 5.2.4 on 2025-09-02 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakinguseranswer',
            name='speaking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='speaking.speakingmaterial'),
        ),
    ]
