# Generated by Django 5.2.4 on 2025-09-07 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0002_alter_speakinguseranswer_speaking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speakinguseranswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='speakinguseranswer',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='speakinguseranswer',
            unique_together={('user', 'speaking', 'question_number')},
        ),
    ]
