# Generated by Django 5.2.4 on 2025-09-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_testaccept_listening_materials_and_more'),
        ('speaking', '0003_alter_speakinguseranswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingmaterial',
            name='test_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_materials', to='app.testmaterial'),
        ),
    ]
