# Generated by Django 5.2.4 on 2025-10-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0004_alter_speakingmaterial_test_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakinguseranswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Speaking Answer', 'verbose_name_plural': 'Speaking Answers'},
        ),
    ]
