# Generated by Django 5.2.4 on 2025-09-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testaccept',
            old_name='test',
            new_name='test_material',
        ),
    ]
