# Generated by Django 5.2.4 on 2025-09-04 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_test_testaccept_test_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedip',
            name='port',
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Agar user tanlansa, IP cheklovi yo‘q', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
