# Generated by Django 5.2.4 on 2025-09-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_allowedip_port_alter_allowedip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedip',
            name='device_uuid',
            field=models.CharField(blank=True, help_text='Hardware UUID (Device identifier)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Agar user tanlansa, IP va device UUID cheklovi yo'q", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='allowedip',
            unique_together={('ip_address', 'device_uuid')},
        ),
    ]
