# Generated by Django 5.2.4 on 2025-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_allowedip_device_uuid_alter_allowedip_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_number',
            field=models.CharField(blank=True, editable=False, max_length=60, unique=True),
        ),
    ]
