# Generated by Django 5.2.4 on 2025-09-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_test_test_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmaterial',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
