# Generated by Django 5.2.4 on 2025-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testmaterial_is_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmaterial',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
