# Generated by Django 5.2.4 on 2025-09-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_testmaterial_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmaterial',
            name='enabled',
        ),
    ]
