# Generated by Django 5.2.4 on 2025-09-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_testmaterial_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaterial',
            name='is_view',
            field=models.BooleanField(default=False, help_text='Is view answer for mock test user or not'),
        ),
    ]
