# Generated by Django 5.2.4 on 2025-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_testmaterial_is_view'),
        ('listening', '0001_initial'),
        ('reading', '0001_initial'),
        ('speaking', '0003_alter_speakinguseranswer_unique_together_and_more'),
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testaccept',
            name='listening_materials',
            field=models.ManyToManyField(blank=True, to='listening.listeningmaterial'),
        ),
        migrations.AddField(
            model_name='testaccept',
            name='reading_materials',
            field=models.ManyToManyField(blank=True, to='reading.readingmaterial'),
        ),
        migrations.AddField(
            model_name='testaccept',
            name='speaking_materials',
            field=models.ManyToManyField(blank=True, to='speaking.speakingmaterial'),
        ),
        migrations.AddField(
            model_name='testaccept',
            name='writing_materials',
            field=models.ManyToManyField(blank=True, to='writing.writingmaterial'),
        ),
    ]
