# Generated by Django 5.2.4 on 2025-09-10 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_testaccept_listening_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaterial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_materials', to='app.test'),
        ),
    ]
