# Generated by Django 5.2.4 on 2025-09-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_testmaterial_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaterial',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test'),
        ),
    ]
