# Generated by Django 5.2.4 on 2025-09-19 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_testmaterial_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedip',
            options={'verbose_name': 'Allowed IP/Device', 'verbose_name_plural': 'Allowed IPs/Devices'},
        ),
        migrations.RemoveField(
            model_name='allowedip',
            name='user',
        ),
        migrations.AddField(
            model_name='allowedip',
            name='users',
            field=models.ManyToManyField(blank=True, help_text="Agar user tanlansa, IP va device UUID cheklovi yo'q", to=settings.AUTH_USER_MODEL),
        ),
    ]
