# Generated by Django 5.2.4 on 2025-09-19 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_allowedip_options_remove_allowedip_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedip',
            name='description',
            field=models.CharField(blank=True, help_text='Bu IP/Device/User haqida izoh', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allowedip',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Faol yoki faol emas'),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address yoki subnet', null=True),
        ),
        migrations.AlterField(
            model_name='allowedip',
            name='users',
            field=models.ManyToManyField(blank=True, help_text="Agar user tanlansa, IP va device UUID cheklovi yo'q - istalgan device dan kirishi mumkin", to=settings.AUTH_USER_MODEL),
        ),
    ]
