# Generated by Django 5.2.4 on 2025-09-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_allowedip_description_allowedip_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Group'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Group Name'),
        ),
    ]
