# Generated by Django 5.2.4 on 2025-12-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_studentgroup_is_active_alter_studentgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_parse',
            field=models.BooleanField(default=True, help_text='If False, questions in reading and listening will be displayed as-is without parsing', verbose_name='Parse Questions'),
        ),
    ]
