# Generated by Django 5.2.4 on 2026-09-21 15:44

import apps.app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_users_is_parse'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', apps.app.models.UsersManager()),
            ],
        ),
    ]
