# Generated by Django 5.2.4 on 2025-08-31 12:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_section', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4')])),
                ('questions', ckeditor.fields.RichTextField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='listening_audios/')),
                ('audioscript', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_script', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Listenings',
                'verbose_name_plural': 'Listenings',
            },
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(default=1, verbose_name='Question Number')),
                ('true_answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correct Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='listening.listening')),
            ],
            options={
                'verbose_name': 'Listening Question',
                'verbose_name_plural': 'Listening Questions',
            },
        ),
        migrations.CreateModel(
            name='ListeningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.PositiveIntegerField(default=3600, verbose_name='Answer Time (seconds)')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='listening_audios/')),
                ('test_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='listening',
            name='listening_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sections', to='listening.listeningmaterial'),
        ),
        migrations.AlterUniqueTogether(
            name='listening',
            unique_together={('listening_material', 'listening_section')},
        ),
        migrations.CreateModel(
            name='ListeningUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='Question Number')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='User Answer')),
                ('is_true', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='listening.listening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_user_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listening Answer',
                'verbose_name_plural': 'Listening Answers',
                'unique_together': {('user', 'listening', 'question_number')},
            },
        ),
    ]
