# Generated by Django 5.2.4 on 2025-10-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0002_alter_listeningmaterial_answer_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningmaterial',
            name='audio',
        ),
        migrations.AlterField(
            model_name='listeningmaterial',
            name='answer_time',
            field=models.PositiveIntegerField(default=3600, verbose_name='Answer Time (seconds)'),
        ),
    ]
