# Generated by Django 5.2.4 on 2025-10-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0004_alter_listeningmaterial_answer_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeninguseranswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Listening Answer', 'verbose_name_plural': 'Listening Answers'},
        ),
    ]
