# Generated by Django 5.2.4 on 2025-11-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0005_alter_listeninguseranswer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeninguseranswer',
            options={'verbose_name': 'Listening Answer', 'verbose_name_plural': 'Listening Answers'},
        ),
    ]
