# Generated by Django 5.2.4 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listening", "0007_listening_questions_raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="listeninganswer",
            name="question",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Write the question. For MCQ put options on new lines, e.g. A) ... B) ... C) ... D) ...",
                verbose_name="Question",
            ),
        ),
    ]
