# Generated by Django 5.2.4 on 2026-09-21 17:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0008_listeninganswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='is_script',
            field=models.BooleanField(default=False, help_text='If enabled, the audio transcript is shown on the left side of the student exam.', verbose_name='Show transcript'),
        ),
        migrations.AlterField(
            model_name='listening',
            name='questions',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
